name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull OWASP ZAP Docker Image
      - name: Pull OWASP ZAP Docker Image
        run: docker pull owasp/zap2docker-stable

      # Run OWASP ZAP Security Scan using docker run cmd
      - name: Run OWASP ZAP Security Scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://your-app-url -g gen.conf -r zap_report.html

      # Upload ZAP Report as artifact
      - name: Upload ZAP Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
