name: Dependency-Check Scan.

on:
  push:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP Dependency-Check
        run: |
          docker pull owasp/dependency-check:latest
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v /tmp/dependency-check:/report \
            owasp/dependency-check:latest --project "MyProject" --scan /src --out /report --format "HTML"

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: /tmp/dependency-check/*.html
